apiVersion: v1
kind: Service
metadata: 
  name: node-todo-service
spec:
  type: NodePort  # Explicitly set the service type to NodePort
  selector:
    app: node-todo
  ports:
    - protocol: TCP
      port: 8000       # Port the service listens on
      targetPort: 8000 # Port the Pod listens on
      nodePort: 30856  # Port on the Node (optional; can be auto-assigned)
